//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top2004
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablesModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablesModel()
        {
            this.newEquipment = new HashSet<newEquipment>();
        }
    
        public int intModelID { get; set; }
        public string strName { get; set; }
        public Nullable<int> intManufacturerID { get; set; }
        public Nullable<int> intSMCSFamilyID { get; set; }
        public string strImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newEquipment> newEquipment { get; set; }
        public virtual TablesManufacturer TablesManufacturer { get; set; }
    }
}
